name: demo
on: 
  workflow_dispatch:
  push:
    branches:
      - 'master'

jobs:
  test-code:
    runs-on: ubuntu-22.04 
    steps:
      - name: checkout code
        uses: actions/checkout@v3
      - name: check docker
        run: docker version
