name: demo
on: 
  workflow_dispatch:
  push:
    branches:
      - 'master'

jobs:
  test-code:
    runs-on: ubuntu-22.04
    steps:
      - name: checkout code
        uses: actions/checkout@v3
      # - uses: actions/setup-python@v4
      #   with:
      #     python-version: 3.8
      - name: install requirements
        run: pip install -r requirements.txt
      - name: run py test
        id: run-py-test
        run: pytest --cov-report html:htmlcov --cov-report term --cov=project tests
      - name: upload test reports
        if: failure() && steps.run-py-test.outcome == 'failure'
        uses: actions/upload-artifact@v3
        with:
          name: test-report
          path: htmlcov/
  
  deploy:
    runs-on: ubuntu-22.04
    #if: ${{ failure() }}
    if: success()
    needs: test-code
    steps:
      - name: checkout code
        uses: actions/checkout@v3
      - name: deploy code
        run: echo "deploy........."