name: demo
on: 
  workflow_dispatch:
  push:
    branches:
      - 'master'

jobs:
  test-code:
    runs-on: ubuntu-22.04
    steps:
      - name: checkout code
        uses: actions/checkout@v3
      - name: install requirements
        run: pip install -r requirements.txt
      - name: run py test
        run: pytest --cov-report html:htmlcov --cov-report term --cov=project tests
      - name: upload test reports
        uses: actions/upload-artifact@v3
        with:
          name: test-report
          path: htmlcov/
  
  deploy:
    runs-on: ubuntu-22.04
    steps:
      - name: checkout code
        uses: actions/checkout@v3
      - name: deploy code
        run: echo "deploy........."